### ISSUE TITLE
Building c3sc

### ISSUE THREAD

**Issue by revolutionized** [goroda/c3sc#1]
Hey just a simple question - I'm trying to build the c3sc library. My folders are c3 and c3sc. Inside c3sc i have a build directory. When I go to build from in there i get
fatal error: c3/array.h No such file or directory.

The c3 library I built fine by following the installation instructions. I tried to replicate that here. What am I doing wrong?

**Comment by goroda** [comment]
Do you have the c3 software installed?
 If you run sudo make install in the c3 software then it should make a c3
subdirectory in usr/local/include. Then when you install c3sc it should
find the headers in the path.

Let me know if this doesn't work.

Alex

**Comment by revolutionized** [comment]
Ah yes I forgot about that!
I got further now but still having troubles.This is the problem now

`/c3sc/src/util.c:44:31: fatal error: cdyn/src/simulate.h: No such file or directory
compilation terminated.
src/CMakeFiles/c3sc.dir/build.make:182: recipe for target 'src/CMakeFiles/c3sc.dir/util.c.o' failed

make[2]: *** [src/CMakeFiles/c3sc.dir/util.c.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/c3sc.dir/all' failed
make[1]: *** [src/CMakeFiles/c3sc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

I'm gonna keep trying to find the problem myself but if you have any suggestions let me know.
Cheers

**Comment by goroda** [comment]
You also need to download and install the cdyn library from my
github. You may have to go through the same process with that as for c3.

Alex


revolutionized writes:

> Ah yes I forgot about that!
> I got further now but still having troubles.This is the problem now
>
> `/c3sc/src/util.c:44:31: fatal error: cdyn/src/simulate.h: No such file or directory
> compilation terminated.
> src/CMakeFiles/c3sc.dir/build.make:182: recipe for target 'src/CMakeFiles/c3sc.dir/util.c.o' failed
>
> make[2]: *** [src/CMakeFiles/c3sc.dir/util.c.o] Error 1
> CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/c3sc.dir/all' failed
> make[1]: *** [src/CMakeFiles/c3sc.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> `
>
> I'm gonna keep trying to find the problem myself but if you have any suggestions let me know.
> Cheers


-- 
Alex A. Gorodetsky
http://www.alexgorodetsky.com
